### ISSUE TITLE
Uncaught TypeError: Cannot read property 'groups' of null

### ISSUE THREAD

**Issue by Slothturtle** [ramtinsoltani/atom-ascii-tree#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [ascii-tree](https://github.com/ramtinsoltani/atom-ascii-tree) package 1.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'groups' of null

```
At C:\Users\dong-gul_lee\.atom\packages\ascii-tree\lib\ascii-tree.js:85

TypeError: Cannot read property 'groups' of null
    at Object.generate (/packages/ascii-tree/lib/ascii-tree.js:85:73)
    at HTMLElement.asciiTreeGenerate (/packages/ascii-tree/lib/ascii-tree.js:26:41)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:350382)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:348857)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:1:767213)
    at EventEmitter.t (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:1:775181)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (~/AppData/Local/atom/app-1.55.0/resources/electron.asar/renderer/init.js:42:16)
```

### Commands

```
     -4:49.1.0 core:backspace (input.hidden-input)
     -4:47.5.0 core:save (input.hidden-input)
     -4:46.3.0 script:run (input.hidden-input)
     -2:50.8.0 ascii-tree:generate (div.tool-panel.tree-view)
     -2:48 encoding-selector:show (atom-text-editor.editor)
     -2:35.6.0 core:backspace (input.hidden-input)
     -2:35.2.0 core:delete (input.hidden-input)
     -2:27.9.0 ascii-unicode-escape:convert (input.hidden-input)
     -2:18.4.0 auto-encoding-for-ruby:add-encoding (input.hidden-input)
     -2:14.7.0 script:run (input.hidden-input)
  2x -2:10.3.0 core:delete (input.hidden-input)
     -1:38.7.0 tree:generate (input.hidden-input)
     -1:20.9.0 ascii-unicode-escape:convert (input.hidden-input)
     -1:18.1.0 script:run (input.hidden-input)
     -0:31.1.0 ascii-tree:reverse (input.hidden-input)
     -0:26.1.0 ascii-tree:generate (input.hidden-input)
```

### Non-Core Packages

```
ascii-tree 1.2.1 
ascii-unicode-escape 0.2.2 
atom-ide-ui 0.13.0 
auto-encoding 0.7.2 
auto-encoding-for-ruby 1.0.4 
emmet 2.4.3 
script 3.31.1 
tree 0.2.0 
```

**Comment by ramtinsoltani** [comment]
@Slothturtle Can you please provide your input which caused this error?

**Comment by KaziiTheAvali** [comment]
im having the same problem. 
i use atom for notes and use trees normally and it wolnt ascii tree this
perseve 
+------look at the problem
prepare
+------prepair for the job
perform
+------perform to go above the job
persevere
+--------outlast the possison

**Comment by ramtinsoltani** [comment]
@KaziiTheAvali I'm afraid you're using a wrong syntax. That error means the regular expressions could not match the syntax of the input.

Try this instead:
```
+-- look at the problem
prepare
+-- prepair for the job
perform
+-- perform to go above the job
persevere
    +-- outlast the possison
```

which will be converted to:
```
├── look at the problem
├── prepair for the job
└── perform to go above the job
    └── outlast the possison
```

Here's the documentation: https://github.com/ramtinsoltani/atom-ascii-tree#example
